# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Build
      run: go build
      working-directory: ./workshop-service

  dockerhub-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: login to docker hub
      id: docker-hub
      env:
        username: ${{secrets.DOCKERHUB_TOKEN}}
        password: ${{secrets.DOCKERHUB_USER}}
      run: |
        docker login -u $username -p $password
    - name: build the docker image
      id: build-docker-image
      run: |
        ls -la 
        docker build . -f Dockerfile -t aelm-workshop-23
    - name: push the docker image
      id: push-docker-image
      run: docker push ${{secrets.DOCKERHUB_USER}}/aelm-workshop-23
